### ISSUE TITLE
"Failed to activate the Remote-FTP package" after update to 10.0.4

### ISSUE THREAD

**Issue by frankIT** [icetee/remote-ftp#664]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Debian GNU/Linux
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.10.4

### Stack Trace

Failed to activate the Remote-FTP package

```
At File.properties is not a function

TypeError: File.properties is not a function
    at /home/fra/.atom/packages/Remote-FTP/lib/file.js:10:8
    at Object.<anonymous> (/home/fra/.atom/packages/Remote-FTP/lib/file.js:58:2)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/fra/.atom/packages/Remote-FTP/lib/directory.js:4:10)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/fra/.atom/packages/Remote-FTP/lib/client.js:9:60)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/fra/.atom/packages/Remote-FTP/lib/remote-ftp.js:4:24)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
```

### Commands

```
     -0:14.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "Remote-FTP": {
    "hideLocalWhenDisplayed": true
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.10.4
activate-power-mode, v1.1.0
atom-meld, v0.2.1
autoclose-html, v0.23.0
django-templates, v0.5.0
file-icons, v1.7.25
language-smarty, v1.7.0
minimap, v4.25.7
symbol-gen, v1.3.1
symbols-tree-view, v0.13.2

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Did you try to re-install?

**Comment by frankIT** [comment]
sure, I saw [this issue](https://github.com/mgrenier/remote-ftp/issues/76), so I re-installed several times, even restarting atom.

**Comment by jpxd** [comment]
Can you please try the dev branch?

```
git clone https://github.com/mgrenier/remote-ftp.git
cd remote-ftp
git checkout dev
apm install
amp link
```

**Comment by frankIT** [comment]
worked as a charm, thank you.

**Comment by jpxd** [comment]
Good :)
An apm update will come in the next days

**Comment by jpxd** [comment]
Should be fixed with version 0.10.5

**Comment by ciambellino** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04.3
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package, v1.2.5


### Stack Trace

Failed to activate the Remote-FTP package

```
At Proxy is not defined

ReferenceError: Proxy is not defined
    at Object.<anonymous> (/home/federico/.atom/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:711:24)
    at Object.<anonymous> (/home/federico/.atom/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:721:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/federico/.atom/packages/Remote-FTP/lib/client.js:15:15)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/federico/.atom/packages/Remote-FTP/lib/remote-ftp.js:4:24)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:173:16)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:29
```

### Commands

```
     -0:50.8.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-ftp-editor"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v1.2.5

# Dev
No dev packages
```

**Comment by icetee** [comment]
@ciambellino I think this is Atom bug. https://github.com/atom/fs-plus/issues/38
Please upgrade your Atom editor and check.

**Comment by svvIrkLife** [comment]
Cannot read property 'destroy' of undefined
Hide Stack Trace
TypeError: Cannot read property 'destroy' of undefined
    at Object.deactivate (file:///C:/Users/Вадим/.atom/packages/Remote-FTP/lib/remote-ftp.js:134:29)
    at Object.activate (file:///C:/Users/Вадим/.atom/packages/Remote-FTP/lib/remote-ftp.js:26:12)
    at Package.module.exports.Package.activateNow (C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:253:25)
    at C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:225:38
    at Package.module.exports.Package.measure (C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:99:21)
    at C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:218:32
    at Package.module.exports.Package.activate (C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:215:40)
    at PackageManager.activatePackage (C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\src\package-manager.js:690:42)
    at packagesToEnable.forEach.name (C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\src\package-manager.js:439:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\src\package-manager.js:439:30)
    at C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\src\config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\src\config.js:884:35)
    at Config.module.exports.Config.setRawValue (C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\src\config.js:670:25)
    at Config.module.exports.Config.set (C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\src\config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\src\config.js:407:18)
    at Package.module.exports.Package.enable (C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:84:32)
    at PackageManager.enablePackage (C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\src\package-manager.js:245:18)
    at HTMLButtonElement.enablementButtonClickHandler (C:\Users\Вадим\AppData\Local\atom\app-1.22.1\resources\app\node_modules\settings-view\lib\package-card.js:361:31)

atom 1.22.1 x64
win 10

Error after remote-ftp update on 2.1.0
